//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSMEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public decimal MontantVente { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
